apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-app-deployment
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: asia.gcr.io/windows-vue-to-the-cloud/windows-vue:0b35f6d
        ports:
        - containerPort: 80
