apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-deployment
  labels:
    app: {{ .Values.appname }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: asia.gcr.io/windows-vue-to-the-cloud/windows-vue:0b35f6d
        ports:
        - containerPort: {{ .Values.appport }}
